#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

# used to make the entrypoint a pass through to ensure that Docker runs the command the user passes in
exec "$@"